usuarios = [    
    {'nome': 'Lucas', 'idade': 23},    
    {'nome': 'Ana', 'idade': 45},    
    {'nome': 'Pedro', 'idade': 32},    
    {'nome': 'Maria', 'idade': 27},    
    {'nome': 'João', 'idade': 18},    
    {'nome': 'Carla', 'idade': 38},    
    {'nome': 'Fernando', 'idade': 56},    
    {'nome': 'Larissa', 'idade': 21},    
    {'nome': 'Ricardo', 'idade': 29},    
    {'nome': 'Júlia', 'idade': 34},    
    {'nome': 'Eduardo', 'idade': 42},    
    {'nome': 'Marcelo', 'idade': 25},    
    {'nome': 'Mariana', 'idade': 31},    
    {'nome': 'Isabella', 'idade': 19},    
    {'nome': 'Rodrigo', 'idade': 37},    
    {'nome': 'Camila', 'idade': 30},    
    {'nome': 'Gustavo', 'idade': 26},    
    {'nome': 'Bianca', 'idade': 24},    
    {'nome': 'Alexandre', 'idade': 47},    
    {'nome': 'Patricia', 'idade': 33},
    ]
